<a href="https://colab.research.google.com/github/Siddhant9633/Data_Science_Lab/blob/main/PR3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import NumPy
import numpy as np

# -----------------------------------
# 1. Create Matrix
# -----------------------------------

A = np.array([[2, 3],
              [1, 4]])

B = np.array([[5],
              [6]])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

# -----------------------------------
# 2. Determinant of Matrix
# -----------------------------------

det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

# -----------------------------------
# 3. Inverse of Matrix
# -----------------------------------

if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("\nInverse of A:\n", inv_A)
else:
    print("\nMatrix is singular, inverse not possible")

# -----------------------------------
# 4. Solve Linear Equation AX = B
# -----------------------------------

X = np.linalg.solve(A, B)
print("\nSolution of AX = B:\n", X)

Matrix A:
 [[2 3]
 [1 4]]

Matrix B:
 [[5]
 [6]]

Determinant of A: 5.000000000000001

Inverse of A:
 [[ 0.8 -0.6]
 [-0.2  0.4]]

Solution of AX = B:
 [[0.4]
 [1.4]]


In [2]:
# -----------------------------------
# 1. Matrix Input
# -----------------------------------

A = [[2, 3],
     [1, 4]]

B = [[5],
     [6]]

print("Matrix A:")
for row in A:
    print(row)

print("\nMatrix B:")
for row in B:
    print(row)

# -----------------------------------
# 2. Determinant (2x2)
# -----------------------------------

det_A = (A[0][0] * A[1][1]) - (A[0][1] * A[1][0])
print("\nDeterminant of A:", det_A)

# -----------------------------------
# 3. Inverse (2x2)
# Formula:
# 1/det * [d  -b
#          -c  a]
# -----------------------------------

if det_A != 0:
    inv_A = [
        [ A[1][1]/det_A, -A[0][1]/det_A],
        [-A[1][0]/det_A,  A[0][0]/det_A]
    ]

    print("\nInverse of A:")
    for row in inv_A:
        print(row)
else:
    print("\nInverse not possible (determinant = 0)")

# -----------------------------------
# 4. Solve AX = B
# Using X = A⁻¹ * B
# -----------------------------------

if det_A != 0:
    X = [
        [inv_A[0][0]*B[0][0] + inv_A[0][1]*B[1][0]],
        [inv_A[1][0]*B[0][0] + inv_A[1][1]*B[1][0]]
    ]

    print("\nSolution X:")
    for row in X:
        print(row)

Matrix A:
[2, 3]
[1, 4]

Matrix B:
[5]
[6]

Determinant of A: 5

Inverse of A:
[0.8, -0.6]
[-0.2, 0.4]

Solution X:
[0.40000000000000036]
[1.4000000000000004]
